In [1]:
import pandas as pd
import sqlite3

conn =sqlite3.connect("School.db")

In [2]:
students=pd.read_csv("students.csv")
courses=pd.read_csv("courses.csv")
enrollments=pd.read_csv("enrollments.csv")

In [3]:
students.to_sql("students", conn, if_exists="replace", index=False)
courses.to_sql("courses", conn ,if_exists="replace" ,index=False)
enrollments.to_sql("enrollments" ,conn ,if_exists='replace' ,index=False)

24

In [4]:
def run(query):
    return pd.read_sql_query(query,conn)

In [5]:
query = '''
SELECT * FROM students
'''
run(query)

    student_id     name        city  score
0            1  Youssef       Cairo     88
1            2   Mariam        Giza     72
2            3     Omar       Cairo     95
3            4   Habiba  Alexandria     60
4            5      Ali       Cairo     81
5            6     Nour        Giza     90
6            7   Khaled       Cairo     67
7            8    Salma  Alexandria     98
8            9   Hassan       Aswan     54
9           10   Farida       Cairo     77
10          11    Tarek        Giza     83
11          12    Layla       Cairo     96
12          13     Amir  Alexandria     70
13          14     Dina       Cairo     64
14          15    Karim        Giza     79
15          16     Rana       Cairo     85
16          17  Mostafa       Aswan     58
17          18     Yara       Cairo     91
18          19     Adel  Alexandria     75
19          20     Hana        Giza     62
20          21   Sherif       Cairo     69
21          22    Malak       Cairo     73
22          23     Ziad        Giza     86
23          24     Nada  Alexandria     80

In [6]:
query = '''
SELECT COUNT(*) FROM students
'''
run(query)

   COUNT(*)
0        24

In [7]:
query = '''
SELECT * FROM courses 
'''
run(query)

   course_id course_name    teacher
0        101        Math   Mr. Sami
1        102     Science   Ms. Huda
2        103     English   Mr. Adel
3        104     History   Ms. Mona
4        105    Computer  Mr. Tamer

In [8]:
query = '''
SELECT COUNT(*) FROM courses 
'''
run(query)

   COUNT(*)
0         5

In [9]:
query = '''
SELECT * FROM enrollments
'''
run(query)

    enrollment_id  student_id  course_id
0               1           1        101
1               2           2        102
2               3           3        105
3               4           4        103
4               5           5        101
5               6           6        102
6               7           7        104
7               8           8        105
8               9           9        103
9              10          10        101
10             11          11        105
11             12          12        102
12             13          13        104
13             14          14        103
14             15          15        101
15             16          16        105
16             17          17        102
17             18          18        105
18             19          19        104
19             20          20        103
20             21          21        101
21             22          22        102
22             23          23        105
23             24          24        104

In [10]:
query = '''
SELECT COUNT(*) FROM enrollments
'''
run(query)

   COUNT(*)
0        24

In [11]:
query = '''
SELECT name , score FROM students
WHERE city = 'Cairo'
'''
run(query)

       name  score
0   Youssef     88
1      Omar     95
2       Ali     81
3    Khaled     67
4    Farida     77
5     Layla     96
6      Dina     64
7      Rana     85
8      Yara     91
9    Sherif     69
10    Malak     73

In [12]:
query = '''
SELECT * FROM students
WHERE score >= 90 
ORDER BY score DESC
'''
run(query)

   student_id   name        city  score
0           8  Salma  Alexandria     98
1          12  Layla       Cairo     96
2           3   Omar       Cairo     95
3          18   Yara       Cairo     91
4           6   Nour        Giza     90

In [13]:
query = '''
SELECT * FROM students
WHERE city = 'Giza'
ORDER BY score DESC
LIMIT 3
'''
run(query)

   student_id   name  city  score
0           6   Nour  Giza     90
1          23   Ziad  Giza     86
2          11  Tarek  Giza     83

In [14]:
query = '''
SELECT * FROM students
ORDER BY score DESC
LIMIT 4 OFFSET 3
'''
run(query)

   student_id     name   city  score
0          18     Yara  Cairo     91
1           6     Nour   Giza     90
2           1  Youssef  Cairo     88
3          23     Ziad   Giza     86

In [15]:
query = '''
SELECT students.name AS Student_name ,
       courses.course_name AS Course_Name 
FROM enrollments
JOIN students ON  enrollments.student_id = students.student_id 
JOIN courses ON  enrollments.course_id = courses.course_id
'''
run(query)

   Student_name Course_Name
0       Youssef        Math
1        Mariam     Science
2          Omar    Computer
3        Habiba     English
4           Ali        Math
5          Nour     Science
6        Khaled     History
7         Salma    Computer
8        Hassan     English
9        Farida        Math
10        Tarek    Computer
11        Layla     Science
12         Amir     History
13         Dina     English
14        Karim        Math
15         Rana    Computer
16      Mostafa     Science
17         Yara    Computer
18         Adel     History
19         Hana     English
20       Sherif        Math
21        Malak     Science
22         Ziad    Computer
23         Nada     History